version: '3'
services:    
  mongodb:
    image: mongo
    container_name: server-dashboard-mongodb   
    ports:
      - "27017:27017"
    restart: unless-stopped       
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    networks:
      backend:
        ipv4_address: ${IP_MONGODB}
      
  mongo-express:
    image: mongo-express
    container_name: server-dashboard-mongo-express    
    ports:
      - "8080:8081"
    restart: unless-stopped       
    networks:
      - backend
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_ADMIN_SERVER}
networks:
      backend:
        name: backend
        ipam:
          driver: default
          config:
            - subnet: ${MASK_MONGODB}